//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.06 at 10:20:45 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://scap.nist.gov/schema/cve/0.1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package gov.nist.scap.schema.cve._0;
